dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=bamboo-rs
matrix:
  include:
    # Android
    #    - env: TARGET=aarch64-linux-android DISABLE_TESTS=1
    #      rust: nightly
    #    - env: TARGET=arm-linux-androideabi DISABLE_TESTS=1
    #      rust: nightly
    #    - env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1
    #      rust: nightly
    #    - env: TARGET=i686-linux-android DISABLE_TESTS=1
    #      rust: nightly
    #    - env: TARGET=x86_64-linux-android DISABLE_TESTS=1
    #      rust: nightly
    #
    #    # iOS
    #    - env: TARGET=aarch64-apple-ios DISABLE_TESTS=1
    #      rust: nightly
    #      os: osx
    #    - env: TARGET=armv7-apple-ios DISABLE_TESTS=1
    #      rust: nightly
    #      os: osx
    #    - env: TARGET=armv7s-apple-ios DISABLE_TESTS=1
    #      rust: nightly
    #      os: osx
    #    - env: TARGET=i386-apple-ios DISABLE_TESTS=1
    #      rust: nightly
    #      os: osx
    #    - env: TARGET=x86_64-apple-ios DISABLE_TESTS=1
    #      rust: nightly
    #      os: osx

    # Linux
    #    - env: TARGET=aarch64-unknown-linux-gnu
    #      rust: nightly
    #    - env: TARGET=arm-unknown-linux-gnueabi
    #      rust: nightly
    #    - env: TARGET=armv7-unknown-linux-gnueabihf
    #      rust: nightly
    #    - env: TARGET=i686-unknown-linux-gnu
    #      rust: nightly
    #    - env: TARGET=i686-unknown-linux-musl
    #      rust: nightly
    #    - env: TARGET=mips-unknown-linux-gnu
    #      rust: nightly
    #    - env: TARGET=mips64-unknown-linux-gnuabi64
    #      rust: nightly
    #    - env: TARGET=mips64el-unknown-linux-gnuabi64
    #      rust: nightly
    #    - env: TARGET=mipsel-unknown-linux-gnu
    #      rust: nightly
    #    - env: TARGET=powerpc-unknown-linux-gnu
    #      rust: nightly
    #    - env: TARGET=powerpc64-unknown-linux-gnu
    #      rust: nightly
    #    - env: TARGET=powerpc64le-unknown-linux-gnu
    #      rust: nightly
    #    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    #      rust: nightly
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=thumbv6m-none-eabi IS_NO_STD=1
    rust: nightly
  - env: TARGET=thumbv7em-none-eabi IS_NO_STD=1
    rust: nightly
  - env: TARGET=thumbv7em-none-eabihf IS_NO_STD=1
    rust: nightly
  - env: TARGET=thumbv7m-none-eabi IS_NO_STD=1
    rust: nightly
before_install:
- set -e
- rustup self update
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  api_key:
  secure: "BO2Q7ObEcuXD3LdklmL22OPDe9ZPS7z1MaIHsSMY0R4pG96jivYvpe/E5Pw2C4XnSwEo2ikrKMQIYmeB38WV2gNdBnWYKApCW2DE3E1hSSxM6E+NlgD26T7KQuXaWGV6xkw1AgKQYBsU5PmH2DUWB7RiIx6zfHK//qB3TZKmeD6yDUQYqyT4FhTdBBWQA8OPgO7ChovInwc12DbS2qzST7Bdxb10RsgTZEH4ubEyfKjVIdKS2U5lJgE9+LtlbZy8Jk760kxXk9pjUx5hU/pqPTam9f81QEL4z4LkzIxU8BYS7EnpbdugYFpqpLt8UEqwYT97bSM9gcOCYPlnhr2w+YTdTWlPb8SgZMGgt6c+JM0K7UOVaoPG6OSuC+Vg6WcYKB/6DexeHVA9/ahn9+hK3xecElPt9q65RUBYyclfieyyqWk9DiUA95UQTu6KoqLI2CLu7n4fQfiiqHRSrjQTyrwRn/A+/qR8ihfHLFtaemrdwIUFW1mZnGGjuBIfmZWSXsRBz+0mH5z0rVlD+WrXiGims05Fso471tilD2sWtGaSTZc3P7eDPZQ5LB/ROHaa3fKQuYyPEe1Z1+RtOwUVvuWZ5KVbmb3yAfaeCMMDxZF38nEO0m+DrQfoSPPbYmQd5mKVQERQ8RqvmNTcuKC0MjZf/sHvXQKFxPVQG96GdrU="
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = nightly"
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
