[workspace]

members = [
    "bamboo-core",
    "bamboo-core-test"
    #"generate-test-vectors",
    #"wasm"
]

[profile.release]
codegen-units = 1
opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort'
