[workspace]

members = [
    "bamboo-core",
    "bamboo-core-test",
    #"generate-test-vectors",
    "bamboo-wasm",
    "bamboo-ffi"
]

[profile.release]
codegen-units = 1
opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort'
