[workspace]

members = [
    "bamboo-core",
    "bamboo-core-test",
    "bamboo-cli",
    #"bamboo-log",
    "generate-test-vectors",
    "bamboo-wasm"
]

exclude = [
    "bamboo-log"

]

[profile.release]
codegen-units = 1
opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort'
