[package]
name = "bamboo-rs"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.4"
varu64 = "0.6.1"
lipmaa-link = {git = "https://github.com/pietgeursen/lipmaa-link"}
blake2b_simd = "0.5.3"
ssb-crypto = "0.1.3"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false
