[workspace]

members = [
    "bamboo-c",
    "bamboo-rs-core",
    "bamboo-rs-core-test",
    "bamboo-rs-cli",
    "generate-test-vectors",
    "bamboo-wasm"
]

exclude = [
    "bamboo-rs-log"
]

[profile.release]
codegen-units = 1
#opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort'
