language = "C"

[parse]
parse_deps = true
clean = true
extra_bindings = ["bamboo-rs-core", "blake3", "ed25519-dalek"]
include = ["bamboo-rs-core", "ed25519-dalek", "blake3"]
exclude = ["typenum", "syn"]
  [parse.expand]
    features = []
