language = "C"

[parse]
parse_deps = true
clean = true
extra_bindings = ["bamboo-rs-core-ed25519-yasmf", "yamf-hash", "ed25519-dalek"]
include = ["bamboo-rs-core-ed25519-yasmf", "yamf-hash", "ed25519-dalek"]
exclude = ["typenum", "syn"]
  [parse.expand]
    features = []
