[package]
name = "bamboo-cli"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
edition = "2018"

[dependencies]
bamboo-core = {path = "../bamboo-core"}
clap = {version = "2.33.0", features = ["yaml"]}
rand = "0.7.0"
serde_json = "1.0.40" 
snafu = "0.6.7"
