name: Run Tests 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Build no_std
      run: cd bamboo-rs-core && cargo build --no-default-features --features u64_backend
    - name: Run tests
      run: cargo test
    - name: Run benches
      run: cargo bench
